.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -38,7 +38,7 @@ jobs:
         # run json server container which will serve the private resume data (its about to become not private, but just the subset we want to publish)
         docker run -d -p 3002:3002 --name jsonserver --network my_network ghcr.io/blademccool/resumedata:$RESUMEDATA_REF
         
-        docker run -d -p 3003:3002 --name jsonserver2 --network host ghcr.io/blademccool/resumedata:$RESUMEDATA_REF
+        # docker run -d -p 3003:3002 --name jsonserver2 --network host ghcr.io/blademccool/resumedata:$RESUMEDATA_REF
 
         # run resume container
         docker run --rm -p 3000:3000 -d --name resume --network my_network ghcr.io/blademccool/resume:$RESUME_REF
@@ -51,21 +51,18 @@ jobs:
         docker ps
         
         #debug output confirm json server is running (should print some HTML about needing JS to run etc.)
-        echo "test jsonserver 1"
-        curl -v http://localhost:3002?baseline=chrono
-
-        echo "test jsonserver 2"
-        curl -v http://localhost:3003?baseline=chrono
+        echo "test jsonserver"
+        curl -i --fail-with-body http://localhost:3002?baseline=chrono
         
-        #debug output confirm react app is running (should print some HTML about needing JS to run etc.)
-        echo "test react app output"
-        curl -v http://localhost:3000?jsonserver=localhost:3002&baseline=chrono
+        #debug output confirm react app is running (should print some HTML about needing JS to run etc - just want to ensure it is being served and reachable)
+        echo "test react app HTML output"
+        curl -i --fail-with-body http://localhost:3000
         
         # run gotenberg
         docker run --rm -p 80:80 -d --network my_network gotenberg/gotenberg:8 gotenberg --api-port=80 --api-timeout=10s --libreoffice-disable-routes --log-level=debug
         # direct gotenberg to produce a pdf and output into ./web which will be bundled into the docker image.
         # curl -v --fail --request POST http://localhost:80/forms/chromium/convert/url --form "url=http://resume?jsonserver=jsonserver:3002&baseline=chrono" --form "waitForExpression=window.contentLoaded===true" -o ./web/Chris_Hagglund_Resume.pdf  || { echo "PDF generation failed"; exit 1; }
-        curl -v --fail --request POST http://localhost:80/forms/chromium/convert/url --form "url=http://resume?jsonserver=jsonserver:3002&baseline=chrono" -o ./web/Chris_Hagglund_Resume.pdf  || { echo "PDF generation failed"; exit 1; }
+        curl -i --fail --request POST http://localhost:80/forms/chromium/convert/url --form "url=http://resume?jsonserver=jsonserver:3002&baseline=chrono" -o ./web/Chris_Hagglund_Resume.pdf  || { echo "PDF generation failed"; exit 1; }
         echo "PDF generated successfully. (contents remain to be verified)"
 
         # Run Ghostscript to convert the PDF to text and check for errors
